services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: netcheck
      POSTGRES_PASSWORD: netcheck
      POSTGRES_DB: netcheck
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: